<?php
if (!defined('EXTERNAL')) {
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>'.$sg->config->gallery_name.' '.$sg->pageTitle().'</title>
<style type="text/css">@import url("'.$sg->config->base_url.$sg->config->pathto_current_template.'css/layout.css");</style>
<style type="text/css">@import url("'.$sg->config->base_url.$sg->config->pathto_current_template.'css/color_'.$sg->config->template_scheme.'.css");</style>
<!--[if IE]><link rel="stylesheet" type="text/css" media="all" href="'.$sg->config->base_url.$sg->config->pathto_current_template.'css/ie.css"><![endif]-->
'.$sg->navigationLinks().'</head>
<body>';
}
?>

<!-- 
	This page was generated by singapore <http://singapore.sourceforge.net>
	singapore is free software licensed under the terms of the GNU GPL.
-->
<div id="sgContainer">
	<div id="sgHeader">
		<div id="sgOptions"><?php echo $sg->languageFlipper(); ?><?php echo $sg->templateFlipper(); ?></div>		
		<div class="sgCrumb"><?php echo $sg->crumbLine(); ?></div>

<!-- start of generated content -->