<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $sg->pageTitle(); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $sg->config->base_url.$sg->config->pathto_current_template ?>main.css" />
<?php echo $sg->navigationLinks(); ?>
<!-- 
  This page was generated by singapore <http://singapore.sourceforge.net>
  singapore is free software licensed under the terms of the GNU GPL.
-->
</head>

<body>

<?php echo $sg->languageFlipper(); ?> 
<?php echo $sg->templateFlipper(); ?>

<div id="crumb"><?php echo $sg->crumbLine(); ?></div>

<div id="header"><img src="<?php echo $sg->config->base_url.$sg->config->pathto_current_template ?>images/header.gif" alt="<?php echo$sg->config->gallery_name ?>" /></div>

<!-- start of generated content -->

