<?php 

 /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\ 
 *  header.php - Copyright 2003 Tamlyn Rhodes <tam@zenology.org>       *
 *                                                                     *
 *  This file is part of singapore v0.9.4a                             *
 *                                                                     *
 *  singapore is free software; you can redistribute it and/or modify  *
 *  it under the terms of the GNU General Public License as published  *
 *  by the Free Software Foundation; either version 2 of the License,  *
 *  or (at your option) any later version.                             *
 *                                                                     *
 *  singapore is distributed in the hope that it will be useful,       *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty        *
 *  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            *
 *  See the GNU General Public License for more details.               *
 *                                                                     *
 *  You should have received a copy of the GNU General Public License  *
 *  along with this; if not, write to the Free Software Foundation,    *
 *  Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA      *
 \* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
 
//this line must be present in any custom headers if you 
//want to display the script execution timer
$scriptStartTime = microtime();

if(empty($pageTitle)) $pageTitle = $sgConfig->site_name;

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $pageTitle ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS["sgConfig"]->pathto_current_theme ?>main.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS["sgConfig"]->pathto_extra_css ?>" />
<!-- 
  This file was generated by singapore <http://singapore.sourceforge.net>
  Singapore is free software released under the terms of the GNU GPL.
-->
</head>

<body>

<div id="header"><img src="<?php echo $GLOBALS["sgConfig"]->pathto_current_theme ?>header.gif" alt="<?php echo $sgConfig->site_name ?>" /></div>

<!-- start of generated content -->

