<?php 

 /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *\ 
 *  header.php - Copyright 2003 Tamlyn Rhodes <tam@zenology.org>       *
 *                                                                     *
 *  This file is part of singapore v0.9.3                              *
 *                                                                     *
 *  singapore is free software; you can redistribute it and/or modify  *
 *  it under the terms of the GNU General Public License as published  *
 *  by the Free Software Foundation; either version 2 of the License,  *
 *  or (at your option) any later version.                             *
 *                                                                     *
 *  singapore is distributed in the hope that it will be useful,       *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty        *
 *  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            *
 *  See the GNU General Public License for more details.               *
 *                                                                     *
 *  You should have received a copy of the GNU General Public License  *
 *  along with this; if not, write to the Free Software Foundation,    *
 *  Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA      *
 \* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

$scriptStartTime = microtime();

if(empty($pageTitle)) $pageTitle = "singapore";
$pathto_current_theme = sgGetConfig("pathto_themes").sgGetConfig("theme_name");
$pathto_main_css = $pathto_current_theme."/main.css";
$pathto_extra_css = sgGetConfig("pathto_extra_css")==""?$pathto_current_theme."/extra.css":sgGetConfig("pathto_extra_css");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $pageTitle ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" type="text/css" href="<?php echo $pathto_main_css ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $pathto_extra_css ?>" />
<!-- 
  This file was generated by singapore <http://singapore.sourceforge.net>
  Singapore is free software released under the terms of the GNU GPL.
-->
</head>

<body>

<div id="header"><img src="<?php echo $pathto_current_theme."/header.gif" ?>" alt="singapore" /></div>

<!-- start of generated content -->
